@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.ofek2608.deep_pocket_conversions.registry;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;