@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.ofek2608.deep_pocket.registry.items.crafting_pattern;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;