@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.ofek2608.deep_pocket.registry.interfaces;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;