@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.ofek2608.deep_pocket.network;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;