@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.ofek2608.deep_pocket.utils;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;